export const MLIT_STANDARDS = [
    {
        "id": "photo-r06",
        "category": "デジタル写真",
        "type": "photo",
        "year": 2024,
        "period": "R6.4.1 以降 契約",
        "standard_name": "デジタル写真管理情報基準（令和6年3月）",
        "versionTag": "デジタル写真管理情報基準 令和6年3月",
        "majorCategory": "工事",
        "summary": "最新のデジタル写真管理情報基準。令和6年3月の改定内容を反映。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/photo9.pdf"
    },
    {
        "id": "photo-r05",
        "category": "デジタル写真",
        "type": "photo",
        "year": 2023,
        "period": "R5.4.1 ～ R6.3.31 契約",
        "standard_name": "デジタル写真管理情報基準（令和5年4月）",
        "versionTag": "デジタル写真管理情報基準 令和5年4月",
        "majorCategory": "工事",
        "summary": "工事・業務において撮影されたデジタル写真の納品形式、フォルダ構成、管理情報の記録形式を規定。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/photo9.pdf"
    },
    {
        "id": "photo-r02",
        "category": "デジタル写真",
        "type": "photo",
        "year": 2020,
        "period": "R2.4.1 ～ R5.3.31 契約",
        "standard_name": "デジタル写真管理情報基準（令和2年4月）",
        "versionTag": "デジタル写真管理情報基準 令和2年4月",
        "majorCategory": "工事",
        "summary": "工事・業務において撮影されたデジタル写真の納品形式に関する基準（旧版）。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/photo8.pdf"
    },
    {
        "id": "photo-h28",
        "category": "デジタル写真",
        "type": "photo",
        "year": 2016,
        "period": "H28.4.1 ～ R2.3.31 契約",
        "standard_name": "デジタル写真管理情報基準（平成28年4月）",
        "versionTag": "デジタル写真管理情報基準 平成28年4月",
        "majorCategory": "工事",
        "summary": "長期にわたり広く適用されたデジタル写真の管理情報記録形式（旧版）。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/code_m5.pdf",
        "comparison_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/comp_code_m5.pdf",
        "point_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/youryou_point_201603.pdf"
    },
    {
        "id": "const-r05",
        "category": "土木工事",
        "type": "construction",
        "year": 2023,
        "period": "R5.4.1 以降 契約",
        "standard_name": "工事完成図書の電子納品等要領（令和5年4月）",
        "summary": "国土交通省が発注する直轄土木工事の完成図書を電子納品するための標準的なルール。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/const_m91.pdf",
        "commentary_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/const_m92.pdf"
    },
    {
        "id": "const-r04",
        "category": "土木工事",
        "type": "construction",
        "year": 2022,
        "period": "R4.4.1 ～ R5.3.31 契約",
        "standard_name": "工事完成図書の電子納品等要領（令和4年4月）",
        "summary": "直轄土木工事の工事完成図書を電子納品するための基準（旧版）。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/const_m81.pdf",
        "commentary_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/const_m82.pdf"
    },
    {
        "id": "const-r03",
        "category": "土木工事",
        "type": "construction",
        "year": 2021,
        "period": "R3.4.1 ～ R4.3.31 契約",
        "standard_name": "工事完成図書の電子納品等要領（令和3年4月）",
        "summary": "直轄土木工事の工事完成図書を電子納品するための基準（旧版）。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/const91.pdf",
        "commentary_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/const92.pdf",
        "comparison_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/comp_const9.pdf",
        "appendix_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/app_const9.pdf"
    },
    {
        "id": "design-r06",
        "category": "土木業務",
        "type": "design",
        "year": 2024,
        "period": "R6.4.1 以降 契約",
        "standard_name": "土木設計業務等の電子納品要領（令和6年4月）",
        "summary": "土木設計業務や調査業務の成果品を電子納品するための基本ルールとフォルダ構成。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/design_e81.pdf",
        "commentary_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/design_e82.pdf",
        "comparison_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/comp_design_e8.pdf",
        "point_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/youryou_point_202403.pdf"
    },
    {
        "id": "design-r05",
        "category": "土木業務",
        "type": "design",
        "year": 2023,
        "period": "R5.4.1 ～ R6.3.31 契約",
        "standard_name": "土木設計業務等の電子納品要領（令和5年4月）",
        "summary": "土木設計業務成果品の電子納品に関する基準（旧版）。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/design_m81.pdf",
        "commentary_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/design_m82.pdf"
    },
    {
        "id": "design-r04",
        "category": "土木業務",
        "type": "design",
        "year": 2022,
        "period": "R4.4.1 ～ R5.3.31 契約",
        "standard_name": "土木設計業務等の電子納品要領（令和4年4月）",
        "summary": "土木設計業務成果品の電子納品に関する基準（旧版）。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/design81.pdf"
    },
    {
        "id": "cad-r08",
        "category": "CAD",
        "type": "cad",
        "year": 2026,
        "period": "R8.4.1 適用",
        "standard_name": "CAD製図基準（令和8年4月適用）",
        "summary": "電子納品におけるCAD図面のレイヤ構成、線種、文字サイズ等の製図ルール（最新）。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/cad8.pdf",
        "commentary_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/cad8_manu.pdf",
        "comparison_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/comp_cad8_manu.pdf",
        "point_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/CAD_point_202512.pdf"
    },
    {
        "id": "cad-h29",
        "category": "CAD",
        "type": "cad",
        "year": 2017,
        "period": "H29.4.1 適用",
        "standard_name": "CAD製図基準（平成29年4月）",
        "summary": "電子納品におけるCAD図面の製図ルール（旧版）。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/cad_m6.pdf",
        "comparison_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/comp_cad_m6_manu.pdf",
        "commentary_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/cad_m6_manu.pdf",
        "point_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/geo_point_201610.pdf"
    },
    {
        "id": "sokuryo-r08",
        "category": "測量",
        "type": "survey",
        "year": 2026,
        "period": "R8.4.1 適用",
        "standard_name": "測量成果電子納品要領（令和8年4月適用）",
        "summary": "数値地形図や路線測量等の公共測量成果を電子納品するための基準（最新）。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/sokuryou70.pdf",
        "comparison_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/comp_sokuryou71.pdf"
    },
    {
        "id": "sokuryo-r06",
        "category": "測量",
        "type": "survey",
        "year": 2024,
        "period": "R6.4.1 適用",
        "standard_name": "測量成果電子納品要領（令和6年4月）",
        "summary": "公共測量成果の電子納品に関する基準（旧版）。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/design_e81.pdf",
        "commentary_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/design_e82.pdf",
        "comparison_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/comp_design_e8.pdf",
        "point_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/youryou_point_202403.pdf"
    },
    {
        "id": "boring-h29",
        "category": "地質",
        "type": "geology",
        "year": 2017,
        "period": "H29.4.1 適用",
        "standard_name": "地質・土質調査成果電子納品要領（平成29年4月）",
        "summary": "ボーリング柱状図等の地質調査結果をXML形式等で電子納品するための基準。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/cad_m6.pdf",
        "comparison_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/comp_cad_m6_manu.pdf",
        "commentary_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/cad_m6_manu.pdf",
        "point_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/geo_point_201610.pdf"
    },
    {
        "id": "design-e-r06",
        "category": "電気通信",
        "type": "telecom",
        "year": 2024,
        "period": "R6.4.1 以降 契約",
        "standard_name": "土木設計業務等の電子納品要領 電気通信設備編（令和6年4月）",
        "summary": "電気通信設備に関わる設計・調査業務成果の納品基準。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/design_e81.pdf",
        "commentary_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/design_e82.pdf",
        "comparison_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/comp_design_e8.pdf",
        "point_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/youryou_point_202403.pdf"
    },
    {
        "id": "const-e-r05",
        "category": "電気通信",
        "type": "telecom",
        "year": 2023,
        "period": "R5.4.1 以降 契約",
        "standard_name": "工事完成図書の電子納品等要領 電気通信設備編（令和5年4月）",
        "summary": "電気通信設備工事における成果品の納品基準。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/const_m91.pdf",
        "commentary_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/const_m92.pdf"
    },
    {
        "id": "design-m-r06",
        "category": "機械設備",
        "type": "machinery",
        "year": 2024,
        "period": "R6.4.1 以降 契約",
        "standard_name": "土木設計業務等の電子納品要領 機械設備工事編（令和6年4月）",
        "summary": "機械設備の設計・調査業務に関する成果品の納品基準。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/design_m91.pdf",
        "commentary_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/design_m92.pdf",
        "comparison_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/comp_design_m9.pdf",
        "point_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/youryou_point_202403.pdf"
    },
    {
        "id": "const-m-r05",
        "category": "機械設備",
        "type": "machinery",
        "year": 2023,
        "period": "R5.4.1 以降 契約",
        "standard_name": "工事完成図書の電子納品等要領 機械設備工事編（令和5年4月）",
        "summary": "機械設備工事に関する成果品の納品基準。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/const_m91.pdf",
        "commentary_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/const_m92.pdf"
    },
    {
        "id": "online-c-r07",
        "category": "オンライン",
        "type": "online",
        "year": 2025,
        "period": "R7.4.1 適用",
        "standard_name": "オンライン電子納品実施要領【工事編】（令和7年4月適用）",
        "summary": "竣工する工事をオンラインで電子納品するための基準。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/online_ed4.pdf",
        "comparison_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/comp_online_ed4.pdf"
    },
    {
        "id": "online-d-r07",
        "category": "オンライン",
        "type": "online",
        "year": 2025,
        "period": "R7.4.1 適用",
        "standard_name": "オンライン電子納品実施要領【業務編】（令和7年4月適用）",
        "summary": "完了する業務をオンラインで電子納品するための基準。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/online_ed_d2.pdf",
        "comparison_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/comp_online_ed_d2.pdf"
    },
    {
        "id": "comp_const-mn2cdfh6-anm89",
        "category": "その他",
        "type": "comp_const",
        "year": null,
        "period": "（第3版正誤訂正版2024.3.5掲載）",
        "standard_name": "（第3版正誤訂正版2024.3.5掲載）",
        "summary": "公式サイトより自動取得された基準資料。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/comp_const111.pdf",
        "comparison_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/comp_design_m8.pdf",
        "point_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/youryou_point_202303.pdf"
    },
    {
        "id": "comp_const-mn2cdfh6-2q89r",
        "category": "その他",
        "type": "comp_const",
        "year": null,
        "period": "（第3版正誤訂正版2022.12.13掲載）",
        "standard_name": "（第3版正誤訂正版2022.12.13掲載）",
        "summary": "公式サイトより自動取得された基準資料。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/comp_const10.pdf",
        "comparison_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/comp_const_m8.pdf",
        "point_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/youryou_em_point_202203.pdf"
    },
    {
        "id": "design-mn2cdfh6-8feey",
        "category": "その他",
        "type": "design",
        "year": null,
        "period": "（第2版正誤訂正版2022.12.13掲載）",
        "standard_name": "（第2版正誤訂正版2022.12.13掲載）",
        "summary": "公式サイトより自動取得された基準資料。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/design82.pdf",
        "commentary_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/design82.pdf"
    },
    {
        "id": "youryou_point-mn2cdfh6-29ui2",
        "category": "その他",
        "type": "youryou_point",
        "year": null,
        "period": "不明な基準",
        "standard_name": "不明な基準",
        "summary": "公式サイトより自動取得された基準資料。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/youryou_point_202103.pdf",
        "point_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/CAD_point_201703.pdf",
        "commentary_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/boring73.pdf",
        "comparison_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/comp_boring73.pdf"
    },
    {
        "id": "const-mn2cdfh6-kwmla",
        "category": "その他",
        "type": "const",
        "year": null,
        "period": "令和2年4月1日以降に契約を締結する工事から適用",
        "standard_name": "令和2年4月1日以降に契約を締結する工事から適用",
        "summary": "公式サイトより自動取得された基準資料。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/const81.pdf",
        "commentary_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/const82.pdf"
    },
    {
        "id": "comp_const-mn2cdfh6-cgfsv",
        "category": "その他",
        "type": "comp_const",
        "year": null,
        "period": "（正誤訂正版2020.07.14 掲載）",
        "standard_name": "（正誤訂正版2020.07.14 掲載）",
        "summary": "公式サイトより自動取得された基準資料。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/comp_const8.pdf",
        "comparison_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/comp_const8.pdf",
        "point_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/youryou_point_202003.pdf"
    },
    {
        "id": "design-mn2cdfh6-ytvto",
        "category": "その他",
        "type": "design",
        "year": null,
        "period": "令和2年4月1日以降に契約を締結する業務から適用",
        "standard_name": "令和2年4月1日以降に契約を締結する業務から適用",
        "summary": "公式サイトより自動取得された基準資料。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/design71.pdf",
        "commentary_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/design72.pdf"
    },
    {
        "id": "comp_design-mn2cdfh6-vbxd7",
        "category": "その他",
        "type": "comp_design",
        "year": null,
        "period": "（正誤訂正版2021.3.24 掲載）",
        "standard_name": "（正誤訂正版2021.3.24 掲載）",
        "summary": "公式サイトより自動取得された基準資料。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/comp_design7.pdf",
        "comparison_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/comp_design7.pdf"
    },
    {
        "id": "const-mn2cdfh6-6tixw",
        "category": "その他",
        "type": "const",
        "year": null,
        "period": "平成31年4月1日以降に契約を締結する工事から適用",
        "standard_name": "平成31年4月1日以降に契約を締結する工事から適用",
        "summary": "公式サイトより自動取得された基準資料。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/const_m71.pdf",
        "commentary_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/const_m72.pdf"
    },
    {
        "id": "comp_const-mn2cdfh6-2l7v2",
        "category": "その他",
        "type": "comp_const",
        "year": null,
        "period": "（正誤訂正版2019.6.3 掲載）",
        "standard_name": "（正誤訂正版2019.6.3 掲載）",
        "summary": "公式サイトより自動取得された基準資料。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/comp_const7.pdf",
        "comparison_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/comp_code_m7.pdf",
        "point_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/youryou_em_point_201903.pdf"
    },
    {
        "id": "design-mn2cdfh6-bwdcg",
        "category": "その他",
        "type": "design",
        "year": null,
        "period": "平成31年4月1日以降に契約を締結する業務から適用",
        "standard_name": "平成31年4月1日以降に契約を締結する業務から適用",
        "summary": "公式サイトより自動取得された基準資料。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/design_m71.pdf",
        "commentary_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/design_m72.pdf"
    },
    {
        "id": "comp_photo-mn2cdfh6-sqisp",
        "category": "その他",
        "type": "comp_photo",
        "year": null,
        "period": "（正誤訂正版2023.12.1掲載）",
        "standard_name": "（正誤訂正版2023.12.1掲載）",
        "summary": "公式サイトより自動取得された基準資料。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/comp_photo9.pdf",
        "comparison_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/comp_photo9.pdf"
    },
    {
        "id": "comp_photo-mn2cdfh6-2vmbd",
        "category": "その他",
        "type": "comp_photo",
        "year": null,
        "period": "（正誤訂正版2021.3.10 掲載）",
        "standard_name": "（正誤訂正版2021.3.10 掲載）",
        "summary": "公式サイトより自動取得された基準資料。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/comp_photo8.pdf",
        "comparison_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/comp_photo8.pdf"
    },
    {
        "id": "sokuryou-mn2cdfh6-k71oe",
        "category": "その他",
        "type": "sokuryou",
        "year": null,
        "period": "令和3年4月1日以降に契約を締結する業務から適用",
        "standard_name": "令和3年4月1日以降に契約を締結する業務から適用",
        "summary": "公式サイトより自動取得された基準資料。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/sokuryou50.pdf"
    },
    {
        "id": "comp_sokuryou-mn2cdfh6-7qpxc",
        "category": "その他",
        "type": "comp_sokuryou",
        "year": null,
        "period": "（正誤訂正版2021.11.10掲載）",
        "standard_name": "（正誤訂正版2021.11.10掲載）",
        "summary": "公式サイトより自動取得された基準資料。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/comp_sokuryou50.pdf",
        "comparison_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/comp_sokuryou50.pdf",
        "point_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/soku_youryou_point_202103.pdf"
    },
    {
        "id": "boring-mn2cdfh6-b4bzd",
        "category": "その他",
        "type": "boring",
        "year": null,
        "period": "平成29年3月31日までに契約を締結する工事・業務に適用",
        "standard_name": "平成29年3月31日までに契約を締結する工事・業務に適用",
        "summary": "公式サイトより自動取得された基準資料。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/boring61.pdf"
    },
    {
        "id": "boring-mn2cdfh6-7xqdb",
        "category": "その他",
        "type": "boring",
        "year": null,
        "period": "正誤表対応版",
        "standard_name": "正誤表対応版",
        "summary": "公式サイトより自動取得された基準資料。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/boring62.pdf"
    },
    {
        "id": "code_m-mn2cdfh6-eh7cv",
        "category": "その他",
        "type": "code_m",
        "year": null,
        "period": "平成31年4月1日以降に契約を締結する工事・業務から適用",
        "standard_name": "平成31年4月1日以降に契約を締結する工事・業務から適用",
        "summary": "公式サイトより自動取得された基準資料。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/code_m7.pdf"
    },
    {
        "id": "online_ed-mn2cdfh6-nz0go",
        "category": "その他",
        "type": "online_ed",
        "year": null,
        "period": "令和5年2月1日以降に竣工する工事に適用",
        "standard_name": "令和5年2月1日以降に竣工する工事に適用",
        "summary": "公式サイトより自動取得された基準資料。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/online_ed3.pdf"
    },
    {
        "id": "online_ed-mn2cdfh6-cc6bl",
        "category": "その他",
        "type": "online_ed",
        "year": null,
        "period": "令和3年12月1日以降に竣工する工事で上書き登録対応システム利用の工事に適用",
        "standard_name": "令和3年12月1日以降に竣工する工事で上書き登録対応システム利用の工事に適用",
        "summary": "公式サイトより自動取得された基準資料。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/online_ed2.pdf"
    },
    {
        "id": "online_ed-mn2cdfh6-s8by8",
        "category": "その他",
        "type": "online_ed",
        "year": null,
        "period": "令和3年12月1日以降に竣工する工事から適用",
        "standard_name": "令和3年12月1日以降に竣工する工事から適用",
        "summary": "公式サイトより自動取得された基準資料。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/online_ed1.pdf"
    },
    {
        "id": "online_ed_d-mn2cdfh6-zbj4i",
        "category": "その他",
        "type": "online_ed_d",
        "year": null,
        "period": "すべての業務に適用（電子納品を求めない業務を除く）",
        "standard_name": "すべての業務に適用（電子納品を求めない業務を除く）",
        "summary": "公式サイトより自動取得された基準資料。",
        "file_url": "https://www.cals-ed.go.jp/mg/wp-content/uploads/online_ed_d1.pdf"
    },
    {
        "id": "eizen-guide-const",
        "category": "営繕",
        "type": "eizen",
        "majorCategory": "工事",
        "versionTag": "電子納品運用ガイドライン【営繕工事編】 令和4年3月",
        "year": 2022,
        "period": "R4.3 改定",
        "standard_name": "電子納品運用ガイドライン【営繕工事編】",
        "summary": "営繕工事における電子納品の具体的な運用方法を定めたガイドライン。",
        "file_url": "https://www.mlit.go.jp/common/001472905.pdf"
    },
    {
        "id": "eizen-guide-design",
        "category": "営繕",
        "type": "eizen",
        "majorCategory": "業務",
        "versionTag": "電子納品運用ガイドライン【営繕業務編】 令和4年3月",
        "year": 2022,
        "period": "R4.3 改定",
        "standard_name": "電子納品運用ガイドライン【営繕業務編】",
        "summary": "営繕業務における電子納品の具体的な運用方法を定めたガイドライン。",
        "file_url": "https://www.mlit.go.jp/common/001472904.pdf"
    }
];

export const PHOTO_STANDARDS = MLIT_STANDARDS.filter(s => s.type === 'photo');
export const CIVIL_ENG_STANDARDS = MLIT_STANDARDS.filter(s => s.type === 'construction' || s.type === 'const');
export const CIVIL_DESIGN_STANDARDS = MLIT_STANDARDS.filter(s => s.type === 'design');
export const EIZEN_STANDARDS = MLIT_STANDARDS.filter(s => s.type === 'eizen');

export const STANDARDS_MAP = MLIT_STANDARDS.reduce((acc, s) => {
    acc[s.id] = s;
    return acc;
}, {});
